apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgCYDKR4aHUlVh3e8lUB5clf3A3bRJDldctMZfgD4o2I/C5aNR0tuD2I5fM94s9GJ+gt+ZDBm55TYMW28BzkdZ90Ilbi6SF60XQUFZPQivIUxXXRnK2eTzn7Ej6UFQKYKNpGSyWMZVmNmY3U0SiesZRYhcecQkZ9d30fcgquKTS9iXEVDj8GTTzfIahh43VRqT9pUdorGw1jz4/05/GxluEKesBbvFXkEWLoCbw1BSkIttUQ+rEJ075jcJ3J+Q+a6ZMyUZc+b3QQMz2cawuiCLMfCWM2/VIw9RVcCoAEv+I1tPGsvhWqQoZZENVnm2+wiMP8RFVz3sfCd8S08+tVyHxib0lobKeZDQ3obsRG7TSeLs2qb5kzColuwpYah+dh88xKQny5jp1GGXZ3cfKZMHrCudsgUXzWNGcY+qqHjf/iu1uRL8LPWWEZt6FPSDpqBsMvIO4UXVxDNWXZoEtZic0o/H5zIblnSPHcCilrTOMXYiv/Eb8aZFDsRtj7k6lfjyGz6oAfvUnSsDbgQb6wfNH1sbPlXC+g6OVRt5JQJY0M2FxNB1GHEsz21tMq8cp5Z1FIhY4D9ga8dQUKPu7HlSl1V24/bJsAgWXvMNPgHKlcfo5Zbzlr4j/pOunnnc5jFj/k2njmhVRJYneasTxJjK4DczqxLlnspsssGhL/vNgyJ2/Sw79vtY4ELWCFmUaFDRyD1G0++6RYf7Wx8GBmOmNPrmKrPceAGV5s6tKLb4y/M+9rrPQ5L+FGtgbq4QbYysO5q8lMwizVlmORzKnZu5Lslrk8e3cKBvXwepP56rS8FpZ3+URAgRplckara9UfKBpyIXz/E9Z7w0Si0MFyPHDHgsbyiQdL037yCMd3Fy/fNJLsE6+n/0uDXs0w+D/R92fPL1i4IrzQbO10A4/K07I5V9cuAIbi+VKagANV86Q5ot5NtebDmyUG0b1SUpsZG+4h+D6+S9vdY/5fq0K/f8l/GJ65yP7sRP+X0MKogmzAyUsJaMA8Ipen//AhC7cGE11se2mpJLSLL2eTDSdk6D5Nrfr54oWwva36OzuI89mnw+6R4IcUBi/USTTjj78kPOnbwjdvdtUrCI+pa9EuCGjvCGG619X8gXhv1Gnvc86UpIyUUQdNKp02DrmrOjVXOZDzWvfoQk0QvTqttFE/RXrnSoqnWc/+uoxJP3UL30vNr0ktlCENs+lD6PZA4HXKQYztCne4y2wbtfWcrY7XFspAAMAw9soHt/VUFmyt25swHgtnGcdiMLTzgWh20kbofKa/ppDpRv9p0NfOkvX7ZH2co/BhTJgCzbwNikFywluRIXgw6Sl/LLAXbS4loKC1RW9GZS8BHzCxGhQuOEq4Ozu1ECDSYUDqgcwfiZ20suvPryOq0Dlw
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

